# Generated by Django 4.1.4 on 2023-01-06 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 6, 16, 17, 16, 909705)),
        ),
    ]
